import Head from 'next/head';
// import Image from "next/image";
// import { Inter } from "next/font/google";
// import styles from "@/styles/Home.module.css";

// const inter = Inter({ subsets: ["latin"] });

// * third party library imports *
import PropTypes from 'prop-types';
import { gql } from '@apollo/client';
import client from '../lib/apolloClient';

import Sample from '../components/sample';

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
      query {
        allSample {
          title
          slug {
            current
          }
          publishedAt
        }
      }
    `,
  });

  return {
    props: {
      samples: data?.allSample || [],
    },
  };
}

export default function Home({ samples = [] }) {
  return (
    <>
      <Head>
        <title>Andrew&apos;s Voice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Andrew&apos;s Voice</h1>
        <Sample samples={samples} />
      </main>
    </>
  );
}

Home.propTypes = {
  samples: PropTypes.array.isRequired,
};
